### PR TITLE
Add .crypto resolution support

### PR DESCRIPTION
**Pull request by sudoryan**
Adds back .crypto resolution support
Upgrades UD resolution library to 2.1.1 to fix react-native BigInt error

### CODE REVIEW

**Comment by Turtus** [comment]
error: bundling failed: Error: Unable to resolve module `js-sha512` from `node_modules\@ensdomains\address-encoder\lib\index.js`: js-sha512 could not be found within the project.

**Comment by Turtus** [comment]
**https://medium.com/unstoppabledomains/how-to-resolve-crypto-domain-names-82046db0404a**
better to use simpler library that will work - and plz TEST before merging

**Comment by Turtus** [comment]
https://github.com/trustee-wallet/trusteeWallet/commit/07cb79734029da32b77c3a6968f53d2972f5b1a1 please look on new flow - its in beta testing now - where unstoppable actual call is commented out

**Comment by sudoryan** [comment]
Both flows work fine on my machine - this PR and the new commit. Can you explain how you got that bundling error? Is it from building the APK or running the emulator normally?

**Comment by Turtus** [comment]
im just building on android emulator in debug off mode and running... no magic( no sense to build on device as it will give the same error

**Comment by sudoryan** [comment]
Did you rm -rf node_modules and reinstall the packages? I am also running the android emulator with debug mode off and works fine for me

**Comment by Turtus** [comment]
yes i`ve done - the same way i have for previous merge - the one you told also works - but then you actually found the bug with big int and updated lib

as unstoppable are not very complex - just smart contact call - and we have already web3 etc - you can use basic web3 layer for resolving

but if you are sure sure that its my fail in testing - you can compile apk and we will install it on the devices - but please use the code ive commited not to redo twice

**Comment by Turtus** [comment]
image

**Pull request closed without merging**
